networks:
  chalk:
  gcp:
  imds:
    ipam:
      driver: default
      config:
        - subnet: 169.254.169.0/24

services:
  # --------------------------------------------------------------------------
  # CHALK

  chalk:
    build:
      context: .
      target: deps
      args:
        BASE: ${BASE:-alpine}
    command: nimble ${CHALK_BUILD:-release}
    working_dir: $PWD
    environment:
      DEBUG: ${DEBUG:-}
      CHALK_PASSWORD: ${CHALK_PASSWORD:-}
    volumes:
      - $PWD:$PWD
      - $PWD/../nimutils:$PWD/../nimutils
      - $PWD/../con4m:$PWD/../con4m
      # n00b libs
      - ../n00b/build_dev/libn00b.a:/root/.local/c0/libs/libn00b.a
      - ../n00b/build_dev/libn00b.a.p:/root/.local/c0/libs/libn00b.a.p
      - ../n00b/build_dev/subprojects/utf8proc-2.9.0/libutf8proc.a:/root/.local/c0/libs/libutf8proc.a
      - ../n00b/subprojects/libffi-3.4.6/x86_64-pc-linux-musl/.libs/libffi.a:/root/.local/c0/libs/libffi.a
      - ../n00b/subprojects/libbacktrace-531aec7c52b66cd750a28a698f3c060f279b18b0/.libs/libbacktrace.a:/root/.local/c0/libs/libbacktrace.a
      - ../n00b/subprojects/libunibreak-5.1/src/.libs/libunibreak.a:/root/.local/c0/libs/libunibreak.a
      - ../n00b/subprojects/curl-8.9.1/lib/.libs/libcurl.a:/root/.local/c0/libs/libcurl.a
      - ../n00b/subprojects/openssl-3.4.0/libssl.a:/root/.local/c0/libs/libssl.a
      - ../n00b/subprojects/openssl-3.4.0/libcrypto.a:/root/.local/c0/libs/libcrypto.a
      # n00b headers
      - ../n00b/include/n00b.h:/root/.local/c0/include/n00b.h
      - ../n00b/include/hatrack.h:/root/.local/c0/include/hatrack.h
      - ../n00b/include/quark.h:/root/.local/c0/include/quark.h
      - ../n00b/include/vendor.h:/root/.local/c0/include/vendor.h
      - ../n00b/include/adts/:/root/.local/c0/include/adts/
      - ../n00b/include/compiler/:/root/.local/c0/include/compiler/
      - ../n00b/include/core/:/root/.local/c0/include/core/
      - ../n00b/include/crypto/:/root/.local/c0/include/crypto/
      - ../n00b/include/hatrack/:/root/.local/c0/include/hatrack/
      - ../n00b/include/io/:/root/.local/c0/include/io/
      - ../n00b/include/n00b/:/root/.local/c0/include/n00b/
      - ../n00b/include/util/:/root/.local/c0/include/util/
      - ../n00b/include/vendor/:/root/.local/c0/include/vendor/
      # other headers
      - ../n00b/subprojects/libbacktrace-531aec7c52b66cd750a28a698f3c060f279b18b0/backtrace.h:/root/.local/c0/include/backtrace.h
      - ../n00b/subprojects/curl-8.9.1/include/curl/:/root/.local/c0/include/curl/
      - ../n00b/subprojects/libunibreak-5.1/src/linebreak.h:/root/.local/c0/include/linebreak.h
      - ../n00b/subprojects/libunibreak-5.1/src/unibreakbase.h:/root/.local/c0/include/unibreakbase.h
      - ../n00b/subprojects/utf8proc-2.9.0/utf8proc.h:/root/.local/c0/include/utf8proc.h
      # nimutils
      - ../nimutils/nimutils/c/md4nim.h:/root/.local/c0/include/md4nim.h

  # --------------------------------------------------------------------------
  # SERVER

  server:
    build:
      context: ./server
      target: deps
    networks:
      chalk:
        aliases:
          - chalk.local
    ports:
      - 8585:8585
    working_dir: /chalk/server
    volumes:
      - .:/chalk
    environment:
      REDIRECT: https://tls.chalk.local:5858
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "curl -f http://localhost:8585/health"
      start_period: 30s
      interval: 1s

  server-tls:
    build:
      context: ./server
      target: deps
    command: run -r -p 5858 --domain=tls.chalk.local --keyfile=cert.key --certfile=cert.pem --use-existing-cert
    working_dir: /chalk/server
    volumes:
      - .:/chalk
    ports:
      - 5858:5858
    networks:
      chalk:
        aliases:
          - tls.chalk.local
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "curl -f https://localhost:5858/health --insecure"
      start_period: 30s
      interval: 1s

  # --------------------------------------------------------------------------
  # TESTS

  # there is no official imds test container so we have very simple wrapper
  imds:
    build:
      context: ./tests/functional
    entrypoint: uvicorn
    command: app:app --host=0.0.0.0 --port=80 --reload
    working_dir: /imds
    volumes:
      - ./tests/functional/imds:/imds
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "curl -f http://localhost/health"
      start_period: 10s
      interval: 1s
    networks:
      imds:
        ipv4_address: 169.254.169.254
      gcp:
        # XXX for simplicity's sake, use a single imds app server for all
        # of AWS, Azure, GCP
        aliases:
          - metadata.google.internal

  # simple server for serving static files
  static:
    build:
      context: ./tests/functional
    entrypoint: python
    command: -m http.server 8000
    working_dir: /chalk/tests/functional
    volumes:
      - .:/chalk
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "curl -f http://localhost:8000/conftest.py"
      start_period: 10s
      interval: 1s
    networks:
      chalk:

  tests:
    build:
      context: ./tests/functional
      args:
        BASE: ${BASE:-ubuntu}
    entrypoint: ./entrypoint.sh
    cap_add:
      - SYS_PTRACE # for gdb
    security_opt:
      - seccomp=unconfined # for gdb
    volumes:
      - $PWD:$PWD
      - $HOME/.pdbrc.py:/root/.pdbrc.py
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/buildkit:/etc/buildkit
      - /etc/docker:/etc/docker
      - /tmp:/tmp
    working_dir: $PWD/tests/functional
    networks:
      - chalk
      - imds
      - gcp
    depends_on:
      registry:
        condition: service_healthy
      server:
        condition: service_healthy
      server-tls:
        condition: service_healthy
      imds:
        condition: service_healthy
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_PROFILE: ${AWS_PROFILE:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      DOCKER_GIT_CONTEXT_SSH_REPO: ${DOCKER_GIT_CONTEXT_SSH_REPO:-}
      DOCKER_GIT_CONTEXT_TOKEN_REPO: ${DOCKER_GIT_CONTEXT_TOKEN_REPO:-}
      GITHUB_ACTIONS: ${GITHUB_ACTIONS:-}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      IP: ${IP:-} # host IP for docker registry tests
      SSH_KEY: ${SSH_KEY:-}

  # --------------------------------------------------------------------------
  # MISC DEPS

  registry:
    image: registry:2
    ports:
      - "5044:5044"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5044
    networks:
      - chalk
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "echo 'GET / HTTP/1.1' | nc -v localhost 5044"
      start_period: 30s
      interval: 1s

  sqlite:
    image: coleifer/sqlite-web
    volumes:
      - ./server:/server
    environment:
      SQLITE_DATABASE: /server/chalkdb.sqlite
    ports:
      - 18080:8080
    healthcheck:
      test:
        - CMD-SHELL
        - sh -c "echo 'GET / HTTP/1.1' | nc -v localhost 8080"
      start_period: 30s
      interval: 1s
